name: Deployment
on:
  push:
    branches:
      - master
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Output information
        run: | 
           echo "${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Output information
        run: |        
          echo "{{ env.MONGODB_USERNAME }}"
